global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "api"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ "api:${APPLICATION_PORT}" ]

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ "postgres-exporter:9187" ]